RequestNetwork/payments-subgraph

- README.md
- package.json
- schema.graphql
- src/erc20FeeProxy.ts
- src/erc20Proxy.ts
- yarn.lock
Co-authored-by: Benjamin Levesque <benjlevesque@users.noreply.github.com>
> feat: index gasPrice and gasUsed

- abis/EthConversionProxy.json
- abis/EthFeeProxy.json
- scripts/prepare.ts
- src/ethConversionProxy.ts
- src/ethFeeProxy.ts
- subgraph.fantom.yaml
- subgraph.matic.yaml
- subgraph.rinkeby.yaml
> feat: add ETH fee/conversion

- package.json
- scripts/prepare.ts
- subgraph.arbitrum-rinkeby.yaml
- subgraph.arbitrum-testnet.yaml
- yarn.lock
Subgraph for the arbitrum testnet
> feat: arbitrum testnet support

- README.md
- package.json
- scripts/compare.ts
- scripts/monitor.ts
- scripts/networks.ts
- yarn.lock
Introducing 2 tools:
- monitor: checks all known networks for indexing delay
- compare: compares the build output and the deployed version, to see if a subgraph is up-to-date
> feat: subgraph monitoring

- schema.graphql
- src/erc20EscrowToPay.ts
- src/erc20FeeProxy.ts
renamed escrow event initializeEmergencyClaim to initiateEmergencyClaim.
> fix: escrow event name

- abis/EthFeeProxy-0.2.0.json
- abis/EthProxy-0.3.0.json
- package.json
- scripts/networks.ts
- scripts/prepare.ts
- subgraph.arbitrum-one.yaml
- subgraph.avalanche.yaml
- subgraph.bsc.yaml
- subgraph.celo.yaml
- subgraph.fantom.yaml
- subgraph.fuse.yaml
- subgraph.mainnet.yaml
- subgraph.matic.yaml
- subgraph.rinkeby.yaml
- subgraph.xdai.yaml
- yarn.lock
Update all subgraphs with the latest versions of EthereumProxy and EthereumFeeProxy.
Add avalanche subgraph (was deployed but not added to the repo).
> fix: ethereum proxies

- abis/ERC20EscrowToPay.json
- package.json
- subgraph.rinkeby.yaml
- yarn.lock
Updating escrow rinkeby address after adding setters for emergency and frozen periods and using Ownable
> fix: update escrow rinkeby address

- src/near/native.conversion.ts
- src/near/native.ts
These changes have already been deployed.
> fix: NEAR timestamps in seconds

- cli/networks.json
- package.json
- subgraph.optimism.yaml
- yarn.lock
Deployment of optimism subgraph.
> feat: optimism subgraph

- cli/networks.json
- package.json
- subgraph.tombchain.yaml
- yarn.lock
Subgraph for tombchain.
It's not deployed through the hosted service and will be deployed by the tombchain team
> feat: tombchain

- cli/lib/delay.ts
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204053766699979
> chore: add support for Alchemy

- abis/ERC20TransferrableReceivable-0.2.0.json
- subgraph.goerli.yaml
- subgraph.mainnet.yaml
- subgraph.matic.yaml
* Add ERC20TransferableReceivable v0.2.0 ABI
* Update chains where it's deployed: Goerli, Polygon, Mainnet
> feat: add erc20 transferable receivable v2

- .github/workflows/deploy.yaml
- cli/commands/deploy.ts
* Fix environment url for `mantle` and `mantle-testnet`
* Minor formatting and spelling fix
> fix: mantle and mantle-testnet environment url

- .github/workflows/deploy.yaml
* Fixed ternary so Github Actions parses it correctly.
> fix: (2nd attempt) environment url for mantle and mantle-testnet 

- .github/workflows/deploy.yaml
> fix: (5th attempt) mantle url

- .github/workflows/deploy.yaml
Resolves #70 
Changes
* Add manual deployment trigger
> fix: add manual github action deployment trigger

- cli/commands/deploy.ts
Fixes #72
* fix(deploy): add ?. operator, fallback to defaults when not defined
> fix(deploy): add ?. operator, fallback to defaults when not defined

- .github/workflows/deploy.yaml
> fix: deployment workflow

- .github/workflows/deploy.yaml
Deployments were failing due to the following error:
```
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/payments-subgraph/payments-subgraph/.github/actions/deploy'. Did you forget to run actions/checkout before running your local action?
```
> fix: deployment workflow (2 attempt)

- cli/commands/deploy.ts
Mantle deployment wasn't working anymore as we're not providing a token anymore.
> fix: mantle deployment

- .github/workflows/deploy.yaml
- cli/networks.json
- package.json
- subgraph.sepolia.yaml
- yarn.lock
> feat: sepolia network
